# Generated by Django 3.2.4 on 2021-06-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird_app', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-datePosted']},
        ),
    ]
